apiVersion: gitops.kluctl.io/v1beta1
kind: KluctlDeployment
metadata:
  name: cluster-apps-podinfo-dev
  namespace: kluctl-system
spec:
  interval: 1m
  timeout: 5m
  source:
    url: https://github.com/codablock/kluctl-session-merge.git
    path: "cluster-apps/podinfo"

  args:
    cluster_name: {{ args.cluster_name }}
    env_type: non-prod
    env_name: dev
    color_override: orange

  context: default

  prune: true
  delete: true
