apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: podtato
  annotations:
    validate-result.kluctl.io/podinfo: "http://{{ args.env_name }}-podtato.{{ base_dns }}"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ args.env_name }}-podtato.{{ base_dns }}
      http:
        paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: podtato-head-frontend
                  port:
                    number: 9000
