apiVersion: gitops.kluctl.io/v1beta1
kind: KluctlDeployment
metadata:
  name: cluster-gitops
  namespace: kluctl-system
spec:
  interval: 1m
  timeout: 5m
  source:
    url: https://github.com/codablock/kluctl-session-merge.git
    path: "cluster-gitops"

  args:
    cluster_name: {{ args.cluster_name }}

  context: default

  prune: true
  delete: true
