apiVersion: gitops.kluctl.io/v1beta1
kind: KluctlDeployment
metadata:
  name: cluster-apps-podtato-head-test
  namespace: kluctl-system
spec:
  interval: 1m
  timeout: 5m
  source:
    url: https://github.com/codablock/kluctl-session-merge.git
    path: "cluster-apps/podtato-head"

  target: prod

  context: default

  prune: true
  delete: true
